#!/usr/bin/ruby
a = ARGV[0].to_i
b = ARGV[1].to_i
a_inv = (0..25).find { |x| a * x % 26 == 1 }
f = -> x { (((x.ord - 'a'.ord - b) * a_inv) % 26 + 'a'.ord).chr }
STDIN.chars.map(&:downcase).each do |c|
  print ('a' <= c && c <= 'z' ? f[c] : c)
end
